const SET_ACCOUNTS = "SET_ACCOUNTS";
const SET_TOPUP = "SET_TOPUP";
const SET_TOPUP_ERROR = "SET_TOPUP_ERROR";
const TOGGLE_TOPUP_LOADING = "TOGGLE_TOPUP_LOADING";
const SET_TOPUP_REQUEST_DATA = "SET_TOPUP_REQUEST_DATA";
const SET_TOPUP_SUCCESS_DATA = "SET_TOPUP_SUCCESS_DATA";
const TOGGLE_TOPUP_CONFIRM_MODAL = "TOGGLE_TOPUP_CONFIRM_MODAL";

export default {
  SET_ACCOUNTS,
  SET_TOPUP,
  SET_TOPUP_ERROR,
  TOGGLE_TOPUP_LOADING,
  SET_TOPUP_REQUEST_DATA,
  SET_TOPUP_SUCCESS_DATA,
  TOGGLE_TOPUP_CONFIRM_MODAL,
};
